# Étape build
FROM node:18-alpine AS builder
WORKDIR /app

# Installer uniquement les dépendances de prod
COPY package*.json ./
RUN npm ci

# Copier le reste du code
COPY . .

# IMPORTANT : le .env.production doit exister à la racine du projet
RUN npm run build

# Étape runtime
FROM nginx:1.23-alpine

# ⚠️ Ici on ne copie plus de nginx.conf → ton Nginx système fait déjà le reverse proxy
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx","-g","daemon off;"]
