version: '3.8'    # la mention “version” est facultative depuis Compose v3.9,
                  # mais on peut la garder ; elle n’est pas bloquante.

services:
  # ─────────────────────────── Postgres ───────────────────────────
  db:
    image: postgres:14
    container_name: securechat_db
    env_file: .env.docker           # ← POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    healthcheck:                    # garantit que le backend attendra « healthy »
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  # ─────────────────────────── Backend Flask ──────────────────────
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: securechat_backend
    depends_on:
      db:
        condition: service_healthy   # ↳ attend le healthcheck « healthy »
    env_file: .env.docker            # ← DATABASE_URL pointant vers db, SECRET_KEY…
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production         # force le mode prod dans le conteneur
    ports:
      - "5000:5000"
    volumes:
     - ./backend/app/migrations:/app/migrations

  # ─────────────────────────── Frontend (Vue/Nginx) ───────────────
  frontend:
    build:
      context: ./frontend/secure_messagerie
      dockerfile: Dockerfile
    container_name: securechat_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data:
