"""Provision an organisation and administrator account from the CLI."""

from __future__ import annotations

import argparse
import asyncio
import re
import sys
import uuid

from sqlalchemy import select

from app.core.security import get_password_hash
from app.db.session import async_session_factory
from app.models import (
    Organization,
    OrganizationMembership,
    OrganizationRole,
    UserAccount,
    UserProfile,
    UserRole,
)


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or uuid.uuid4().hex[:12]


async def _resolve_organization(session, name: str, slug: str | None) -> Organization:
    normalized_slug = _slugify(slug or name)
    existing = await session.execute(select(Organization).where(Organization.slug == normalized_slug))
    organization = existing.scalar_one_or_none()
    if organization:
        return organization
    organization = Organization(name=name.strip(), slug=normalized_slug)
    session.add(organization)
    await session.flush()
    return organization


async def _resolve_user(session, email: str, password: str, display_name: str | None) -> UserAccount:
    existing = await session.execute(select(UserAccount).where(UserAccount.email == email))
    user = existing.scalar_one_or_none()
    if user:
        # Always ensure the account stays active/confirmed
        user.is_active = True
        user.is_confirmed = True
        if password:
            user.hashed_password = get_password_hash(password)
    else:
        user = UserAccount(
            email=email,
            hashed_password=get_password_hash(password),
            role=UserRole.MEMBER,
            is_active=True,
            is_confirmed=True,
        )
        session.add(user)
        await session.flush()
    profile = user.profile
    if profile is None:
        profile = UserProfile(user_id=user.id)
        session.add(profile)
        user.profile = profile
    if display_name:
        profile.display_name = display_name.strip()
    return user


async def _ensure_membership(
    session,
    *,
    organization: Organization,
    user: UserAccount,
    role: OrganizationRole,
) -> OrganizationMembership:
    stmt = select(OrganizationMembership).where(
        OrganizationMembership.organization_id == organization.id,
        OrganizationMembership.user_id == user.id,
    )
    existing = (await session.execute(stmt)).scalar_one_or_none()
    if existing:
        existing.role = role
        await session.flush()
        return existing
    membership = OrganizationMembership(organization_id=organization.id, user_id=user.id, role=role)
    session.add(membership)
    await session.flush()
    return membership


async def _main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Bootstrap an organisation with an administrator account.")
    parser.add_argument("--email", required=True, help="Email of the administrator account.")
    parser.add_argument("--password", required=True, help="Temporary password to assign.")
    parser.add_argument("--display-name", default="", help="Display name for the administrator.")
    parser.add_argument("--organization", required=True, help="Human-friendly organisation name.")
    parser.add_argument("--slug", default=None, help="Optional organisation slug (autogenerated when omitted).")
    parser.add_argument(
        "--role",
        choices=["owner", "admin"],
        default="owner",
        help="Membership role to assign inside the organisation.",
    )

    args = parser.parse_args(argv)

    async with async_session_factory() as session:
        organization = await _resolve_organization(session, args.organization, args.slug)
        user = await _resolve_user(session, args.email, args.password, args.display_name or args.organization)
        membership = await _ensure_membership(
            session,
            organization=organization,
            user=user,
            role=OrganizationRole.OWNER if args.role == "owner" else OrganizationRole.ADMIN,
        )
        await session.commit()

    print("Organisation:", organization.name, f"(slug={organization.slug})")
    print("User:", user.email, f"(id={user.id})")
    print("Membership:", membership.role.value, f"(id={membership.id})")
    return 0


def run() -> None:
    asyncio.run(_main(sys.argv[1:]))


if __name__ == "__main__":
    run()

