"""auto

Revision ID: 108b072e40f1
Revises: e17c557b5ce4
Create Date: 2025-06-01 08:54:19.397632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108b072e40f1'
down_revision = 'e17c557b5ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
