"""auto

Revision ID: 1a872ccb6855
Revises: de313afadcba
Create Date: 2025-06-01 17:43:43.383025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a872ccb6855'
down_revision = 'de313afadcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_audit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('log_audit_id_user_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'utilisateur', ['id_user'], ['id_user'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_audit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('log_audit_id_user_fkey'), 'utilisateur', ['id_user'], ['id_user'])

    # ### end Alembic commands ###
