"""auto

Revision ID: 56372bcce727
Revises: c3961448f835
Create Date: 2025-05-30 10:42:08.126693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56372bcce727'
down_revision = 'c3961448f835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_totp_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totp_locked_until', sa.DateTime(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('totp_locked_until')
        batch_op.drop_column('failed_totp_attempts')

    # ### end Alembic commands ###
