"""auto

Revision ID: c3961448f835
Revises: 
Create Date: 2025-05-25 11:41:58.765657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3961448f835'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id_conv', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_conv')
    )
    op.create_table('utilisateur',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('pseudo', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('cle_publique', sa.Text(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('archive',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_conv', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_conv'], ['conversation.id_conv'], ),
    sa.ForeignKeyConstraint(['id_user'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_conv')
    )
    op.create_table('contact',
    sa.Column('id_contact', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('pending', 'accepted', 'blocked', name='contact_state'), nullable=False),
    sa.Column('date_maj', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ami_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ami_id'], ['utilisateur.id_user'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('id_contact')
    )
    op.create_table('conv_settings',
    sa.Column('id_conv', sa.Integer(), nullable=False),
    sa.Column('history_mode', sa.Boolean(), nullable=True),
    sa.Column('slow_mode_sec', sa.Integer(), nullable=True),
    sa.Column('allowed_files', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_conv'], ['conversation.id_conv'], ),
    sa.PrimaryKeyConstraint('id_conv')
    )
    op.create_table('device',
    sa.Column('id_device', sa.String(length=36), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('push_token', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('id_device')
    )
    op.create_table('invitation',
    sa.Column('uuid_invite', sa.String(length=36), nullable=False),
    sa.Column('email_cible', sa.String(length=120), nullable=False),
    sa.Column('id_conv', sa.Integer(), nullable=False),
    sa.Column('role_init', sa.Enum('owner', 'admin', 'member', name='user_role'), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_conv'], ['conversation.id_conv'], ),
    sa.PrimaryKeyConstraint('uuid_invite')
    )
    op.create_table('key_pair',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('priv_enc', sa.LargeBinary(), nullable=False),
    sa.Column('pub_key', sa.Text(), nullable=False),
    sa.Column('algo', sa.String(length=20), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('log_audit',
    sa.Column('id_log', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('message',
    sa.Column('id_msg', sa.Integer(), nullable=False),
    sa.Column('contenu_chiffre', sa.Text(), nullable=False),
    sa.Column('ts_msg', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('conv_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.id_conv'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['utilisateur.id_user'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('id_msg')
    )
    op.create_table('participation',
    sa.Column('id_conv', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='user_role'), nullable=False),
    sa.ForeignKeyConstraint(['id_conv'], ['conversation.id_conv'], ),
    sa.ForeignKeyConstraint(['id_user'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('id_conv', 'id_user')
    )
    op.create_table('refresh_token',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('totp_secret',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('secret_base32', sa.String(length=32), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('file',
    sa.Column('id_file', sa.Integer(), nullable=False),
    sa.Column('id_msg', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=80), nullable=True),
    sa.Column('taille', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id_msg'], ['message.id_msg'], ),
    sa.PrimaryKeyConstraint('id_file')
    )
    op.create_table('message_status',
    sa.Column('id_msg', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('etat', sa.Enum('delivered', 'read', name='msg_state'), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_msg'], ['message.id_msg'], ),
    sa.ForeignKeyConstraint(['id_user'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('id_msg', 'id_user')
    )
    op.create_table('reaction',
    sa.Column('id_msg', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_msg'], ['message.id_msg'], ),
    sa.ForeignKeyConstraint(['id_user'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('id_msg', 'id_user', 'emoji')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reaction')
    op.drop_table('message_status')
    op.drop_table('file')
    op.drop_table('totp_secret')
    op.drop_table('refresh_token')
    op.drop_table('participation')
    op.drop_table('message')
    op.drop_table('log_audit')
    op.drop_table('key_pair')
    op.drop_table('invitation')
    op.drop_table('device')
    op.drop_table('conv_settings')
    op.drop_table('contact')
    op.drop_table('archive')
    op.drop_table('utilisateur')
    op.drop_table('conversation')
    # ### end Alembic commands ###
