"""auto

Revision ID: de313afadcba
Revises: 108b072e40f1
Create Date: 2025-06-01 17:23:23.652585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de313afadcba'
down_revision = '108b072e40f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('refresh_token_id_user_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'utilisateur', ['id_user'], ['id_user'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('refresh_token_id_user_fkey'), 'utilisateur', ['id_user'], ['id_user'])

    # ### end Alembic commands ###
