"""auto

Revision ID: e17c557b5ce4
Revises: 25e2a6efebb6
Create Date: 2025-05-31 12:02:48.203998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17c557b5ce4'
down_revision = '25e2a6efebb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_attempt')
    # ### end Alembic commands ###
