"""auto

Revision ID: e31c9d5e5be8
Revises: 56372bcce727
Create Date: 2025-05-30 14:41:43.587330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31c9d5e5be8'
down_revision = '56372bcce727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('owner', 'admin', 'member', name='user_role'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
