"""auto

Revision ID: fc3ab4b4801c
Revises: 71cc54507273
Create Date: 2025-09-23 21:04:31.261107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3ab4b4801c'
down_revision = '71cc54507273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_session',
    sa.Column('id_call', sa.Integer(), nullable=False),
    sa.Column('conv_id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('call_type', sa.Enum('audio', 'video', name='call_type'), nullable=False),
    sa.Column('room_name', sa.String(length=120), nullable=False),
    sa.Column('join_url', sa.String(length=512), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.id_conv'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['utilisateur.id_user'], ),
    sa.PrimaryKeyConstraint('id_call')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_session')
    # ### end Alembic commands ###
